language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mathe-matician/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mathe-matician/docker-react npm run test -- --coverage